//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fish
    {
        public int FishId { get; set; }
        public int StructureTypeId { get; set; }
        public decimal FishLength { get; set; }
        public int FishCount { get; set; }
        public int SpeciesId { get; set; }
        public int SurveyIndex { get; set; }
    
        public virtual Species Species { get; set; }
        public virtual StructureType StructureType { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
