//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishSurvey
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FISHSURVEYEntities : DbContext
    {
        public FISHSURVEYEntities()
            : base("name=FISHSURVEYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Trophic> Trophics { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<StudyArea> StudyAreas { get; set; }
        public virtual DbSet<SubRegion> SubRegions { get; set; }
        public virtual DbSet<BatchCode> BatchCodes { get; set; }
        public virtual DbSet<Fish> Fishes { get; set; }
        public virtual DbSet<Management> Managements { get; set; }
        public virtual DbSet<StructureType> StructureTypes { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
    }
}
