//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.Fishes = new HashSet<Fish>();
        }
    
        public int SurveyIndex { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public System.DateTime SurveyDate { get; set; }
        public int StudyAreaId { get; set; }
        public int ManagementId { get; set; }
        public int BatchCodeId { get; set; }
    
        public virtual StudyArea StudyArea { get; set; }
        public virtual BatchCode BatchCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fish> Fishes { get; set; }
        public virtual Management Management { get; set; }
    }
}
